# build_data.py
import os
import glob
import pandas as pd
import numpy as np
import yfinance as yf
from arch import arch_model
import warnings

warnings.filterwarnings("ignore")

def purge_stale_artifacts():
    """
    Scans the runtime directory and aggressively wipes out stale data cache,
    temporary validation checkpoints, and incomplete model optimization tracking databases.
    """
    print("\n=== SYSTEM SANITIZATION: PURGING STALE ARTIFACTS ===")

    # Target files that introduce historical cache pollution or state corruption
    stale_files = [
        "master_df.csv",
        "test_tft_predictions.csv",
        "tft_nifty_optimization.db",
        "model_validation_master_report.txt"
    ]

    for file in stale_files:
        if os.path.exists(file):
            try:
                os.remove(file)
                print(f"  -> Successfully deleted stale file: {file}")
            except Exception as e:
                print(f"  [WARNING] Could not purge {file}: {str(e)}")

    # Also wipe out residual PyTorch Lightning checkpoints from aborted training sessions
    stale_checkpoints = glob.glob("lightning_logs/*/checkpoints/*.ckpt")
    for ckpt in stale_checkpoints:
        try:
            os.remove(ckpt)
            print(f"  -> Purged abandoned model checkpoint: {ckpt}")
        except Exception as e:
            pass

    print("=== WORKSPACE CLEAR: LAUNCHING FRESH DATA ENGINEING PIPELINE ===\n")

def generate_clean_production_data():
    # 1. Trigger the isolation purge
    purge_stale_artifacts()

    print("[ETL] Fetching historical index spot and macro volatility pairs...")
    # Pull fresh underlying arrays (Using Nifty 50 and US VIX as baseline)
    # Target dates bound out-of-sample matching timelines up to 2026
    nifty = yf.download("^NSEI", start="2015-01-01", end="2026-08-01", progress=False)
    vix = yf.download("^VIX", start="2015-01-01", end="2026-08-01", progress=False)

    if nifty.empty or vix.empty:
        raise ValueError("[FATAL] Yahoo Finance API failure. Unable to download spot sequences.")

    # Calculate daily log returns
    nifty['Log_Ret'] = np.log(nifty['Close'] / nifty['Close'].shift(1)) * 100

    # Structural merge
    df = pd.DataFrame(index=nifty.index)
    df['Log_Ret'] = nifty['Log_Ret']
    df['US_VIX'] = vix['Close']
    df = df.dropna()

    # 2. Fit GJR-GARCH programmatically to extract scale-free innovations
    print("[ECONOMETRICS] Fitting baseline rolling Skew-T GJR-GARCH filter...")
    returns = df['Log_Ret'].values
    am = arch_model(returns, vol='Garch', p=1, o=1, q=1, dist='skewt')
    res = am.fit(disp='off')

    # Store standard conditional volatility and residuals
    df['GARCH_Vol'] = res.conditional_volatility
    df['GARCH_Resid'] = res.resid

    # Derive the mathematical 99% VaR Parametric floor generated by the econometric base
    # q=0.01 threshold maps to the skewed Student-t inverse CDF
    q_dist = res.model.distribution.ppf(0.01, res.params[-2:]) # extract nu and lambda
    df['GARCH_VaR_99'] = res.params['omega'] + df['GARCH_Vol'] * q_dist

    # 3. Generate sequential temporal sequences for the Transformer model
    df = df.reset_index()
    df.rename(columns={df.columns[0]: 'Date'}, inplace=True)
    df['time_idx'] = df.index

    # Feature lag engineering (Lagged inputs to avoid lookahead bias)
    df['Log_Ret_Lag1'] = df['Log_Ret'].shift(1)
    df['Log_Ret_Lag2'] = df['Log_Ret'].shift(2)
    df['VIX_Diff'] = df['US_VIX'].diff()
    df['India_VIX_Diff'] = df['Log_Ret'].rolling(5).std().diff()

    df = df.dropna()

    output_path = "master_df.csv"
    df.to_csv(output_path, index=False)
    print(f"[SUCCESS] Reconstructed clean matrix database at: {output_path}")
    print(f"Total Operational Observations: {len(df)} trading horizons.")

if __name__ == "__main__":
    generate_clean_production_data()
